PREFIX : <http://bizar.aitc.jp/ns/spaceos/0.1/> 
PREFIX ha: <http://bizar.aitc.jp/ns/spaceos/0.1/人間API>
SELECT ?url
WHERE {
      ?room :場所 :ここ .
      ?room :在室 ?p .
      ?c :主人 $p .
      #?c ?x ?o .
      ?c ha:テキストメッセージ ?url .
}
